// =============================================================
//  RanjanTools — Single Source of Truth
//  Add a new entry here and it AUTOMATICALLY appears in:
//  Homepage · Category Pages · Navbar Mega Menu · Search · Footer
// =============================================================

export const categories = [
  {
    id: 'pdf',
    label: 'PDF Tools',
    slug: 'pdf-tools',
    icon: 'file-pdf',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #fef2f2, #fee2e2)',
    gradientDark: 'linear-gradient(135deg, #3f1010, #2d0a0a)',
    description: 'Everything you need for PDF files — merge, split, compress and convert.',
  },
  {
    id: 'image',
    label: 'Image Tools',
    slug: 'image-tools',
    icon: 'picture',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #eff6ff, #dbeafe)',
    gradientDark: 'linear-gradient(135deg, #0f1f40, #0a1628)',
    description: 'Resize, compress, convert and enhance your images in seconds.',
  },
  {
    id: 'utility',
    label: 'Smart Utilities',
    slug: 'smart-utilities',
    icon: 'tool',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #f5f3ff, #ede9fe)',
    gradientDark: 'linear-gradient(135deg, #201040, #160830)',
    description: 'Smart document utilities for students, aspirants and professionals.',
  },
]

export const tools = [
  // ─────────────────────── PDF TOOLS ───────────────────────
  {
    slug: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Merge multiple PDF files into one document instantly.',
    category: 'pdf',
    featured: true,
    implemented: true,
    color: '#5b6af5',
    gradient: 'linear-gradient(135deg, #f0f4ff, #e0e7ff)',
    gradientDark: 'linear-gradient(135deg, #101640, #0a0f2d)',
    icon: 'merge-cells',
    seoTitle: 'Merge PDF Online Free — RanjanTools',
    seoDescription: 'Combine multiple PDF files into one instantly. Free, no sign-up, works in browser.',
    features: [
      { title: '100% Free', desc: 'No hidden charges, no watermarks.' },
      { title: 'No Upload', desc: 'All merging happens in your browser.' },
      { title: 'Fast & Secure', desc: 'Merge in seconds, files never leave your device.' },
    ],
    faqs: [
      { q: 'How many PDFs can I merge?', a: 'You can merge as many PDFs as your browser can handle — typically dozens.' },
      { q: 'Is my data safe?', a: 'Yes! All processing is local in your browser. We never see your files.' },
    ],
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to high-quality JPG images instantly.',
    category: 'pdf',
    featured: true,
    implemented: true,
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #fef2f2, #fee2e2)',
    gradientDark: 'linear-gradient(135deg, #3f1010, #2d0a0a)',
    icon: 'file-pdf',
    seoTitle: 'PDF to JPG Converter Free — RanjanTools',
    seoDescription: 'Convert any PDF page to a high-quality JPG image. Free and instant.',
    features: [
      { title: 'High Quality', desc: 'Export pages at crisp resolution.' },
      { title: 'Page by Page', desc: 'Convert individual or all pages.' },
      { title: 'Instant Download', desc: 'Download converted images immediately.' },
    ],
    faqs: [
      { q: 'What quality are the converted images?', a: 'Images are exported at high resolution suitable for printing and forms.' },
      { q: 'Can I convert multiple pages?', a: 'Yes, you can convert all pages at once and download them individually.' },
    ],
  },
  {
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Split a large PDF into individual pages or custom ranges.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #fff7ed, #ffedd5)',
    gradientDark: 'linear-gradient(135deg, #3f1a0a, #2d1005)',
    icon: 'scissor',
    seoTitle: 'Split PDF Online Free — RanjanTools',
    seoDescription: 'Split any PDF into pages or custom ranges. Free, instant, no sign-up.',
    features: [
      { title: 'Custom Ranges', desc: 'Split pages 1-5, 6-10 or any range.' },
      { title: 'Extract Pages', desc: 'Pull out specific pages from any PDF.' },
      { title: 'Browser-Based', desc: 'No upload needed, fully private.' },
    ],
    faqs: [
      { q: 'Can I extract only specific pages?', a: 'Yes, you can select any range of pages to extract.' },
      { q: 'Is there a file size limit?', a: 'No server limit since processing is done in your browser.' },
    ],
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Compress PDF file size without losing quality.',
    category: 'pdf',
    featured: true,
    implemented: false,
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #f0fdf4, #dcfce7)',
    gradientDark: 'linear-gradient(135deg, #0a2f14, #061e0d)',
    icon: 'compress',
    seoTitle: 'Compress PDF Online Free — RanjanTools',
    seoDescription: 'Reduce PDF file size while preserving quality. Free, no sign-up required.',
    features: [
      { title: 'Smart Compression', desc: 'Optimizes images and fonts inside the PDF.' },
      { title: 'Quality Control', desc: 'Choose compression level to balance size vs quality.' },
      { title: 'Fast Processing', desc: 'Compress in seconds right in your browser.' },
    ],
    faqs: [
      { q: 'Will compression reduce quality?', a: 'Our tool uses smart compression to minimize quality loss.' },
      { q: 'How much can it compress?', a: 'Typically 40-70% reduction depending on the PDF content.' },
    ],
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF. Merge multiple images into one PDF.',
    category: 'pdf',
    featured: false,
    implemented: true,
    color: '#5b6af5',
    gradient: 'linear-gradient(135deg, #f0f4ff, #e0e7ff)',
    gradientDark: 'linear-gradient(135deg, #101640, #0a0f2d)',
    icon: 'file-image',
    seoTitle: 'JPG to PDF Converter Free — RanjanTools',
    seoDescription: 'Convert JPG images to PDF for free. Combine multiple images into one PDF.',
    features: [
      { title: 'Batch Convert', desc: 'Add multiple images at once.' },
      { title: 'Auto Sizing', desc: 'Each image fits perfectly on a PDF page.' },
      { title: 'Free Forever', desc: 'No sign-up, no watermarks.' },
    ],
    faqs: [
      { q: 'Can I merge multiple images into one PDF?', a: 'Yes, upload multiple images and they will each become a page in the PDF.' },
      { q: 'What image formats are supported?', a: 'JPG, PNG, and WEBP are all supported.' },
    ],
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents (.docx) to PDF format online.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#2563eb',
    gradient: 'linear-gradient(135deg, #eff6ff, #dbeafe)',
    gradientDark: 'linear-gradient(135deg, #0f1f40, #0a1628)',
    icon: 'file-word',
    seoTitle: 'Word to PDF Converter Free — RanjanTools',
    seoDescription: 'Convert Word DOCX files to PDF format easily. Free, no software needed.',
    features: [
      { title: 'Format Preserved', desc: 'Fonts, images and layout are kept intact.' },
      { title: 'No Software', desc: 'Works in browser, no MS Word needed.' },
      { title: 'Instant', desc: 'Conversion happens in seconds.' },
    ],
    faqs: [
      { q: 'Will my formatting be preserved?', a: 'Yes, we preserve fonts, images, tables and layout as closely as possible.' },
      { q: 'Is .docx the only format supported?', a: 'Currently .docx format is supported.' },
    ],
  },
  {
    slug: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermark to your PDF files.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#7c3aed',
    gradient: 'linear-gradient(135deg, #f5f3ff, #ede9fe)',
    gradientDark: 'linear-gradient(135deg, #201040, #160830)',
    icon: 'font-colors',
    seoTitle: 'Add Watermark to PDF Free — RanjanTools',
    seoDescription: 'Add text or image watermarks to your PDF. Free online tool, no sign-up.',
    features: [
      { title: 'Text Watermark', desc: 'Add custom text in any font, size and opacity.' },
      { title: 'Positioning', desc: 'Place watermark anywhere on the page.' },
      { title: 'Batch Apply', desc: 'Apply to all pages at once.' },
    ],
    faqs: [
      { q: 'Can I add a logo watermark?', a: 'Currently text watermarks are supported. Image watermarks are coming soon.' },
      { q: 'Can I set opacity?', a: 'Yes, you can adjust the opacity level of the watermark.' },
    ],
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90° or 180° — individual pages or all at once.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #f0f9ff, #e0f2fe)',
    gradientDark: 'linear-gradient(135deg, #0a2636, #061720)',
    icon: 'redo',
    seoTitle: 'Rotate PDF Pages Free — RanjanTools',
    seoDescription: 'Rotate PDF pages 90 or 180 degrees online for free. No upload needed.',
    features: [
      { title: 'Any Angle', desc: 'Rotate 90°, 180° or 270° in either direction.' },
      { title: 'Selective Rotation', desc: 'Rotate specific pages or all at once.' },
      { title: 'Instant Preview', desc: 'See the result before downloading.' },
    ],
    faqs: [
      { q: 'Can I rotate just one page?', a: 'Yes, you can rotate individual pages or all pages at once.' },
      { q: 'Will rotation affect quality?', a: 'No, rotation is lossless — no quality reduction.' },
    ],
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF files.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #fffbeb, #fef3c7)',
    gradientDark: 'linear-gradient(135deg, #2f1e00, #1e1200)',
    icon: 'unlock',
    seoTitle: 'Unlock PDF Free — Remove PDF Password — RanjanTools',
    seoDescription: 'Remove password from PDF files online for free. No sign-up required.',
    features: [
      { title: 'Instant Unlock', desc: 'Remove password protection in one click.' },
      { title: 'Privacy Safe', desc: 'Files stay in your browser — never uploaded.' },
      { title: 'Free', desc: 'No cost, no registration required.' },
    ],
    faqs: [
      { q: 'What if I forgot the password?', a: 'You need to know the password to unlock. We do not crack passwords.' },
      { q: 'Is this safe?', a: 'Yes — processing happens in your browser only.' },
    ],
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to your PDF files.',
    category: 'pdf',
    featured: false,
    implemented: false,
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #ecfdf5, #d1fae5)',
    gradientDark: 'linear-gradient(135deg, #052e16, #031a0d)',
    icon: 'lock',
    seoTitle: 'Protect PDF with Password Free — RanjanTools',
    seoDescription: 'Add password protection to PDF documents. Free, secure, browser-based.',
    features: [
      { title: 'Secure Encryption', desc: 'Industry-standard PDF encryption.' },
      { title: 'Custom Password', desc: 'Set any password you choose.' },
      { title: 'Privacy First', desc: 'Processing stays in your browser.' },
    ],
    faqs: [
      { q: 'How strong is the encryption?', a: 'We use AES-256 encryption — the same standard used by banks.' },
      { q: 'Can I protect with both open and edit passwords?', a: 'Yes, you can set separate passwords for opening and editing.' },
    ],
  },

  // ─────────────────────── IMAGE TOOLS ───────────────────────
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress image to exact KB — 20KB, 50KB, 100KB. Perfect for government forms.',
    category: 'image',
    featured: true,
    implemented: true,
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #f0fdf4, #dcfce7)',
    gradientDark: 'linear-gradient(135deg, #0a2f14, #061e0d)',
    icon: 'compress',
    seoTitle: 'Compress Image to Exact KB — RanjanTools',
    seoDescription: 'Compress your image to exactly 20KB, 50KB or any size. Free, instant, browser-based.',
    features: [
      { title: 'Exact KB Control', desc: 'Set target size to 20KB, 50KB or any value.' },
      { title: 'Preview First', desc: 'See the result before downloading.' },
      { title: 'No Quality Loss', desc: 'Smart compression preserves maximum quality.' },
    ],
    faqs: [
      { q: 'Can I compress to exactly 20KB?', a: 'Yes! Set your target size and we will compress to within a few KB of your target.' },
      { q: 'Which formats are supported?', a: 'JPG, PNG, and WEBP are all supported.' },
    ],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize to exact px, cm or mm. No quality loss. Perfect for exam forms.',
    category: 'image',
    featured: true,
    implemented: true,
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #f5f3ff, #ede9fe)',
    gradientDark: 'linear-gradient(135deg, #201040, #160830)',
    icon: 'expand',
    seoTitle: 'Resize Image Online Free — RanjanTools',
    seoDescription: 'Resize images to exact pixels, cm or mm. Free online image resizer.',
    features: [
      { title: 'Precise Dimensions', desc: 'Enter exact px, cm or mm values.' },
      { title: 'Maintain Ratio', desc: 'Optionally lock aspect ratio.' },
      { title: 'Multiple Formats', desc: 'Export as JPG, PNG or WEBP.' },
    ],
    faqs: [
      { q: 'Can I resize to 3.5cm × 4.5cm for SSC forms?', a: 'Yes! Select cm as unit and enter exact dimensions.' },
      { q: 'Does resizing reduce quality?', a: 'We use high-quality resampling to preserve sharpness.' },
    ],
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between JPG, PNG, WEBP and other image formats instantly.',
    category: 'image',
    featured: true,
    implemented: true,
    color: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #f0f9ff, #e0f2fe)',
    gradientDark: 'linear-gradient(135deg, #0a2636, #061720)',
    icon: 'picture',
    seoTitle: 'Image Converter Online Free — JPG PNG WEBP — RanjanTools',
    seoDescription: 'Convert images between JPG, PNG and WEBP format. Free, instant, no upload.',
    features: [
      { title: 'All Formats', desc: 'JPG, PNG, WEBP, GIF and more.' },
      { title: 'Batch Convert', desc: 'Convert multiple images at once.' },
      { title: 'Quality Control', desc: 'Adjust output quality for each format.' },
    ],
    faqs: [
      { q: 'Which formats can I convert to?', a: 'JPG, PNG, and WEBP are currently supported.' },
      { q: 'Is there a file size limit?', a: 'No server limits — conversion happens in your browser.' },
    ],
  },
  {
    slug: 'remove-background',
    name: 'Remove Background',
    description: 'Remove image background automatically. Get transparent PNG in one click.',
    category: 'image',
    featured: true,
    implemented: false,
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #fdf2f8, #fce7f3)',
    gradientDark: 'linear-gradient(135deg, #3f0f28, #2d0a1c)',
    icon: 'scissor',
    seoTitle: 'Remove Background from Image Free — RanjanTools',
    seoDescription: 'Remove image background automatically and get a transparent PNG. Free online tool.',
    features: [
      { title: 'AI Powered', desc: 'Smart AI detects and removes backgrounds accurately.' },
      { title: 'Transparent PNG', desc: 'Get a clean transparent background PNG.' },
      { title: 'Instant Result', desc: 'Background removed in under 5 seconds.' },
    ],
    faqs: [
      { q: 'How accurate is background removal?', a: 'Works great on photos with clear subjects — portraits, products, etc.' },
      { q: 'Can I replace the background?', a: 'Yes, after removing you can add a solid color or custom background.' },
    ],
  },
  {
    slug: 'crop-image',
    name: 'Crop Image',
    description: 'Crop images to any size or aspect ratio with a visual editor.',
    category: 'image',
    featured: false,
    implemented: false,
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #fff7ed, #ffedd5)',
    gradientDark: 'linear-gradient(135deg, #3f1a0a, #2d1005)',
    icon: 'scissor',
    seoTitle: 'Crop Image Online Free — RanjanTools',
    seoDescription: 'Crop images online with a visual editor. Free, fast, no software needed.',
    features: [
      { title: 'Visual Crop', desc: 'Drag to select the exact area to keep.' },
      { title: 'Aspect Ratios', desc: 'Crop to standard ratios like 1:1, 4:3, 16:9.' },
      { title: 'Free Form', desc: 'Or crop to any custom dimensions you need.' },
    ],
    faqs: [
      { q: 'Can I crop to a specific pixel size?', a: 'Yes, enter exact pixel dimensions for the crop area.' },
      { q: 'What formats are supported?', a: 'JPG, PNG, and WEBP are all supported.' },
    ],
  },
  {
    slug: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate or flip images in any direction. Free online tool.',
    category: 'image',
    featured: false,
    implemented: false,
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #f0fdfa, #ccfbf1)',
    gradientDark: 'linear-gradient(135deg, #0a2f2b, #061e1b)',
    icon: 'redo',
    seoTitle: 'Rotate Image Online Free — RanjanTools',
    seoDescription: 'Rotate images 90, 180, 270 degrees or flip horizontally/vertically. Free.',
    features: [
      { title: 'Any Angle', desc: 'Rotate 90°, 180°, 270° or custom angle.' },
      { title: 'Flip', desc: 'Flip horizontally or vertically.' },
      { title: 'No Quality Loss', desc: 'Lossless rotation preserves original quality.' },
    ],
    faqs: [
      { q: 'Can I rotate to a custom angle?', a: 'Yes, you can enter any angle value.' },
      { q: 'Does rotation affect file size?', a: 'No, rotation does not change the file size.' },
    ],
  },
  {
    slug: 'change-background',
    name: 'Change Background',
    description: 'Change or add background color/image to photos.',
    category: 'image',
    featured: false,
    implemented: false,
    color: '#7c3aed',
    gradient: 'linear-gradient(135deg, #f5f3ff, #ede9fe)',
    gradientDark: 'linear-gradient(135deg, #201040, #160830)',
    icon: 'bg-colors',
    seoTitle: 'Change Image Background Free — RanjanTools',
    seoDescription: 'Change or replace photo background with any color or image. Free online tool.',
    features: [
      { title: 'Solid Colors', desc: 'Replace background with any solid color.' },
      { title: 'Custom Image', desc: 'Upload your own background image.' },
      { title: 'Gradients', desc: 'Apply beautiful gradient backgrounds.' },
    ],
    faqs: [
      { q: 'Can I use a white background for passport photos?', a: 'Yes, simply select white as your background color.' },
      { q: 'Does it work on any photo?', a: 'Works best on photos where the subject is clearly visible.' },
    ],
  },
  {
    slug: 'upscale-image',
    name: 'Upscale Image',
    description: 'Upscale and enhance image resolution using AI. Make small images bigger.',
    category: 'image',
    featured: false,
    implemented: false,
    color: '#0284c7',
    gradient: 'linear-gradient(135deg, #f0f9ff, #e0f2fe)',
    gradientDark: 'linear-gradient(135deg, #0a2636, #061720)',
    icon: 'zoom-in',
    seoTitle: 'Upscale Image Online Free — AI Enhancer — RanjanTools',
    seoDescription: 'Upscale low-resolution images with AI enhancement. Free online image upscaler.',
    features: [
      { title: 'AI Upscaling', desc: 'AI adds detail while upscaling for sharp results.' },
      { title: '2x / 4x', desc: 'Choose 2x or 4x upscale factor.' },
      { title: 'Noise Reduction', desc: 'Removes JPEG artifacts during upscaling.' },
    ],
    faqs: [
      { q: 'How much can I upscale an image?', a: 'Up to 4x the original resolution using AI enhancement.' },
      { q: 'What is the input size limit?', a: 'Images up to 5MB can be upscaled.' },
    ],
  },
  {
    slug: 'date-on-photo',
    name: 'Date on Photo',
    description: 'Add name & date strip to photos for SSC, Railway and government forms.',
    category: 'image',
    featured: true,
    implemented: true,
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #f0fdfa, #ccfbf1)',
    gradientDark: 'linear-gradient(135deg, #0a2f2b, #061e1b)',
    icon: 'calendar',
    seoTitle: 'Add Date on Photo Free — SSC Railway Forms — RanjanTools',
    seoDescription: 'Add name and date stamp to photos for SSC, Railway and government exam forms. Free.',
    features: [
      { title: 'Exam Ready', desc: 'Format meets SSC, Railway and UPSC requirements.' },
      { title: 'Custom Text', desc: 'Add any name, date or custom text.' },
      { title: 'Instant Download', desc: 'Download ready-to-use form photo.' },
    ],
    faqs: [
      { q: 'Is the format accepted by SSC?', a: 'Yes, the output follows the standard format required by most government exams.' },
      { q: 'Can I customize the text and date?', a: 'Yes, you can set any name and date you need.' },
    ],
  },

  // ─────────────────────── SMART UTILITIES ───────────────────────
  {
    slug: 'profile-picture',
    name: 'Profile Picture Maker',
    description: 'Make round profile pictures with border & background. Perfect for WhatsApp, LinkedIn.',
    category: 'utility',
    featured: true,
    implemented: true,
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #fdf2f8, #fce7f3)',
    gradientDark: 'linear-gradient(135deg, #3f0f28, #2d0a1c)',
    icon: 'user',
    seoTitle: 'Profile Picture Maker Free — RanjanTools',
    seoDescription: 'Create round profile pictures with custom borders and backgrounds. Free online tool.',
    features: [
      { title: 'Circle Crop', desc: 'Auto-crops your photo into a perfect circle.' },
      { title: 'Custom Border', desc: 'Add colored borders for a professional look.' },
      { title: 'Background Colors', desc: 'Set custom background behind the circle.' },
    ],
    faqs: [
      { q: 'What size should I use for LinkedIn?', a: 'We recommend 400×400px for LinkedIn profile pictures.' },
      { q: 'Can I add a colored border?', a: 'Yes, pick any border color and width you like.' },
    ],
  },
  {
    slug: 'id-card-joiner',
    name: 'ID Card Joiner',
    description: 'Merge Aadhaar / voter ID front & back into one page. Perfect for forms.',
    category: 'utility',
    featured: true,
    implemented: true,
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #fff7ed, #ffedd5)',
    gradientDark: 'linear-gradient(135deg, #3f1a0a, #2d1005)',
    icon: 'idcard',
    seoTitle: 'ID Card Joiner — Aadhaar Front Back on One Page — RanjanTools',
    seoDescription: 'Merge Aadhaar or voter ID front and back into one A4 page. Free, instant.',
    features: [
      { title: 'A4 Layout', desc: 'Both sides placed neatly on one A4 PDF page.' },
      { title: 'Any ID Card', desc: 'Works with Aadhaar, Voter ID, PAN, Driving License.' },
      { title: 'Instant PDF', desc: 'Download the combined PDF in one click.' },
    ],
    faqs: [
      { q: 'Can I use this for Aadhaar card?', a: 'Yes, upload front and back of Aadhaar and get a combined PDF.' },
      { q: 'Is the layout accepted in forms?', a: 'Yes, the layout follows the standard format required by most institutions.' },
    ],
  },
  {
    slug: 'resume-builder',
    name: 'Resume Builder',
    description: 'Build a professional resume in minutes. Download as PDF for free.',
    category: 'utility',
    featured: true,
    implemented: false,
    color: '#5b6af5',
    gradient: 'linear-gradient(135deg, #f0f4ff, #e0e7ff)',
    gradientDark: 'linear-gradient(135deg, #101640, #0a0f2d)',
    icon: 'file-text',
    seoTitle: 'Free Resume Builder Online — RanjanTools',
    seoDescription: 'Build a professional resume online and download as PDF for free. No sign-up.',
    features: [
      { title: 'Multiple Templates', desc: 'Choose from modern, classic and creative templates.' },
      { title: 'Live Preview', desc: 'See your resume update in real-time as you type.' },
      { title: 'PDF Export', desc: 'Download a print-ready PDF instantly.' },
    ],
    faqs: [
      { q: 'Can I save my resume?', a: 'Your data is saved locally in your browser.' },
      { q: 'Are there multiple templates?', a: 'Yes, multiple professional templates are available.' },
    ],
  },
  {
    slug: 'biodata-maker',
    name: 'Biodata Maker',
    description: 'Create marriage biodata in PDF format. Traditional & modern styles.',
    category: 'utility',
    featured: false,
    implemented: false,
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #fdf2f8, #fce7f3)',
    gradientDark: 'linear-gradient(135deg, #3f0f28, #2d0a1c)',
    icon: 'heart',
    seoTitle: 'Marriage Biodata Maker Free — RanjanTools',
    seoDescription: 'Create marriage biodata and download as PDF. Traditional and modern styles. Free.',
    features: [
      { title: 'Traditional Styles', desc: 'Beautiful traditional Indian biodata templates.' },
      { title: 'Modern Design', desc: 'Clean, modern biodata formats too.' },
      { title: 'PDF Download', desc: 'Download print-ready biodata instantly.' },
    ],
    faqs: [
      { q: 'Can I add a photo to the biodata?', a: 'Yes, you can upload your photo to include in the biodata.' },
      { q: 'Is the biodata printable?', a: 'Yes, the PDF is formatted for standard A4 printing.' },
    ],
  },
  {
    slug: 'cv-builder',
    name: 'CV Builder',
    description: 'Create a detailed CV / curriculum vitae for academic and government jobs.',
    category: 'utility',
    featured: false,
    implemented: false,
    color: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #f0f9ff, #e0f2fe)',
    gradientDark: 'linear-gradient(135deg, #0a2636, #061720)',
    icon: 'file-text',
    seoTitle: 'CV Builder Free — Academic & Government Jobs — RanjanTools',
    seoDescription: 'Create a detailed CV for academic and government job applications. Free PDF download.',
    features: [
      { title: 'Detailed Format', desc: 'Designed for academic and government job applications.' },
      { title: 'Multiple Sections', desc: 'Education, experience, publications, awards and more.' },
      { title: 'ATS Friendly', desc: 'Formats that pass Applicant Tracking Systems.' },
    ],
    faqs: [
      { q: 'What is the difference between a CV and Resume?', a: 'A CV is more detailed and includes publications, awards, and research. Used mostly for academic or government roles.' },
      { q: 'Can I download as PDF?', a: 'Yes, download your completed CV as a professional PDF.' },
    ],
  },
  {
    slug: 'passport-photo',
    name: 'Passport Photo Maker',
    description: 'Create passport-size photos in standard sizes: 35×45mm, 51×51mm.',
    category: 'utility',
    featured: true,
    implemented: false,
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #f0fdf4, #dcfce7)',
    gradientDark: 'linear-gradient(135deg, #0a2f14, #061e0d)',
    icon: 'camera',
    seoTitle: 'Passport Photo Maker Online Free — RanjanTools',
    seoDescription: 'Create passport-size photos in 35x45mm and 51x51mm formats. Free online tool.',
    features: [
      { title: 'Standard Sizes', desc: 'All passport and visa photo sizes supported.' },
      { title: 'White Background', desc: 'Auto white background for compliance.' },
      { title: 'Print Layout', desc: 'Prints multiple photos on one A4 sheet.' },
    ],
    faqs: [
      { q: 'What sizes are supported?', a: 'We support 35×45mm, 51×51mm, and all standard passport photo sizes globally.' },
      { q: 'Will the background be white?', a: 'Yes, white background is applied automatically as required by most passport authorities.' },
    ],
  },
  {
    slug: 'signature-cropper',
    name: 'Signature Cropper',
    description: 'Crop and clean your signature on white background for online forms.',
    category: 'utility',
    featured: false,
    implemented: false,
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #fffbeb, #fef3c7)',
    gradientDark: 'linear-gradient(135deg, #2f1e00, #1e1200)',
    icon: 'edit',
    seoTitle: 'Signature Cropper Free — Online Forms — RanjanTools',
    seoDescription: 'Crop and clean your signature for online form submissions. Free, instant.',
    features: [
      { title: 'Auto Crop', desc: 'Automatically detects and crops around the signature.' },
      { title: 'White Background', desc: 'Cleans the background to white for form compliance.' },
      { title: 'Size Control', desc: 'Resize to exact KB or pixel requirements.' },
    ],
    faqs: [
      { q: 'Can I use a photo of my signature?', a: 'Yes, just take a clear photo on white paper and upload it.' },
      { q: 'What size should the signature be for SSC?', a: 'SSC requires signature between 1KB and 30KB in JPG format.' },
    ],
  },
  {
    slug: 'thumb-impression',
    name: 'Thumb Impression Cropper',
    description: 'Crop and optimize thumb impression images for government forms.',
    category: 'utility',
    featured: false,
    implemented: false,
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #f0fdfa, #ccfbf1)',
    gradientDark: 'linear-gradient(135deg, #0a2f2b, #061e1b)',
    icon: 'highlight',
    seoTitle: 'Thumb Impression Cropper Free — RanjanTools',
    seoDescription: 'Crop and optimize thumb impression for government and exam forms. Free online tool.',
    features: [
      { title: 'Auto Detection', desc: 'Automatically detects the thumb impression area.' },
      { title: 'Size Optimization', desc: 'Reduces to the KB limit required by forms.' },
      { title: 'Clean Output', desc: 'White background for clear, compliant impression.' },
    ],
    faqs: [
      { q: 'What is the required size for thumb impression in SSC?', a: 'Usually between 1KB and 30KB in JPG format.' },
      { q: 'Can I use an ink impression photo?', a: 'Yes, photograph your ink thumb impression on white paper and upload.' },
    ],
  },
]

// ─── Helper utilities ───────────────────────────────────────────

/** Get all tools for a category */
export const getToolsByCategory = (categoryId) =>
  tools.filter((t) => t.category === categoryId)

/** Get featured tools */
export const getFeaturedTools = () => tools.filter((t) => t.featured)

/** Find a tool by slug */
export const getToolBySlug = (slug) => tools.find((t) => t.slug === slug)

/** Get related tools (same category, different slug, up to limit) */
export const getRelatedTools = (slug, limit = 4) =>
  tools
    .filter((t) => t.slug !== slug && t.category === tools.find((x) => x.slug === slug)?.category)
    .slice(0, limit)

/** Search tools */
export const searchTools = (query) => {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  )
}

/** Get category info by id */
export const getCategoryById = (id) => categories.find((c) => c.id === id)
